// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxSVL1BAbRn7YdsTHoY1_tuw41u5Bfmro',
    appId: '1:615412700258:web:44b31a39caf8a075f2ed3b',
    messagingSenderId: '615412700258',
    projectId: 'studify-333',
    authDomain: 'studify-333.firebaseapp.com',
    databaseURL: 'https://studify-333-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'studify-333.appspot.com',
    measurementId: 'G-Y07KC2EGJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGh7JfnzESH-QjJINFxfvgEqEuz1AehGY',
    appId: '1:615412700258:android:38df94be9b0a987df2ed3b',
    messagingSenderId: '615412700258',
    projectId: 'studify-333',
    databaseURL: 'https://studify-333-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'studify-333.appspot.com',
  );
}
